sudo: required
services:
  - docker
language: python
script:
  - python -m unittest tests.operatorTests
  - python -m unittest tests.calcTests
  
  # Static analysis
  - flake8 --statistics --count

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh  